#Chance of a skeleton squad to spawn with a skeleton
#Range: > 1
squadSpawnChance = 500
#Minimal difficulty for a squad to spawn
squadDifficultyMin = 3.5
#Entities to spawn in a squad, in the following order: Skeleton, Knight Skeleton, Haunter Skeleton, Minion.
entityNbList = [2, 1, 2, 6]
#Entities to spawn in a squad (HARD difficulty), in the following order: Skeleton, Knight Skeleton, Haunter Skeleton, Minion.
entityNbListHard = [4, 2, 2, 10]
#A list of items to log on common setup.
items = ["minecraft:iron_ingot"]